create table public.sys_countries (
  name      text,
  iso2      text                      not null primary key,
  iso3      text                      not null,
  enabled   boolean   default false   not null
);

insert into public.sys_countries (name, iso2, iso3) values
  ('Bonaire, Sint Eustatius and Saba','BQ', 'BES'),
  ('Curaçao','CW', 'CUW'),
  ('Guernsey','GG', 'GGY'),
  ('Isle of Man','IM','IMN'),
  ('Jersey','JE','JEY'),
  ('Åland Islands','AX','ALA'),
  ('Montenegro','ME','MNE'),
  ('Saint Barthélemy','BL','BLM'),
  ('Saint Martin (French part)','MF','MAF'),
  ('Serbia','RS','SRB'),
  ('Sint Maarten (Dutch part)','SX','SXM'),
  ('South Sudan','SS','SSD'),
  ('Timor-Leste','TL','TLS'),
  ('American Samoa','as','ASM'),
  ('Andorra','AD','AND'),
  ('Angola','AO','AGO'),
  ('Anguilla','AI','AIA'),
  ('Antarctica','AQ','ATA'),
  ('Antigua and Barbuda','AG','ATG'),
  ('Argentina','AR','ARG'),
  ('Armenia','AM','ARM'),
  ('Aruba','AW','ABW'),
  ('Australia','AU','AUS'),
  ('Austria','AT','AUT'),
  ('Azerbaijan','AZ','AZE'),
  ('Bahamas','BS','BHS'),
  ('Bahrain','BH','BHR'),
  ('Bangladesh','BD','BGD'),
  ('Barbados','BB','BRB'),
  ('Belarus','BY','BLR'),
  ('Belgium','BE','BEL'),
  ('Belize','BZ','BLZ'),
  ('Benin','BJ','BEN'),
  ('Bermuda','BM','BMU'),
  ('Bhutan','BT','BTN'),
  ('Bolivia','BO','BOL'),
  ('Bosnia and Herzegovina','BA','BIH'),
  ('Botswana','BW','BWA'),
  ('Bouvet Island','BV','BVT'),
  ('Brazil','BR','BRA'),
  ('British Indian Ocean Territory','IO','IOT'),
  ('Brunei Darussalam','BN','BRN'),
  ('Bulgaria','BG','BGR'),
  ('Burkina Faso','BF','BFA'),
  ('Burundi','BI','BDI'),
  ('Cambodia','KH','KHM'),
  ('Cameroon','CM','CMR'),
  ('Canada','CA','CAN'),
  ('Cape Verde','CV','CPV'),
  ('Cayman Islands','KY','CYM'),
  ('Central African Republic','CF','CAF'),
  ('Chad','TD','TCD'),
  ('Chile','CL','CHL'),
  ('China','CN','CHN'),
  ('Christmas Island','CX','CXR'),
  ('Cocos (Keeling) Islands','CC','CCK'),
  ('Colombia','CO','COL'),
  ('Comoros','KM','COM'),
  ('Congo','CG','COG'),
  ('Congo, the Democratic Republic of the','CD','COD'),
  ('Cook Islands','CK','COK'),
  ('Costa Rica','CR','CRI'),
  ('Cote DIvoire','CI','CIV'),
  ('Croatia','HR','HRV'),
  ('Cuba','CU','CUB'),
  ('Cyprus','CY','CYP'),
  ('Czech Republic','CZ','CZE'),
  ('Denmark','DK','DNK'),
  ('Djibouti','DJ','DJI'),
  ('Dominica','DM','DMA'),
  ('Dominican Republic','DO','DOM'),
  ('Ecuador','EC','ECU'),
  ('Egypt','EG','EGY'),
  ('El Salvador','SV','SLV'),
  ('Equatorial Guinea','GQ','GNQ'),
  ('Eritrea','ER','ERI'),
  ('Estonia','EE','EST'),
  ('Ethiopia','ET','ETH'),
  ('Falkland Islands (Malvinas)','FK','FLK'),
  ('Faroe Islands','FO','FRO'),
  ('Fiji','FJ','FJI'),
  ('Finland','FI','FIN'),
  ('France','FR','FRA'),
  ('French Guiana','GF','GUF'),
  ('French Polynesia','PF','PYF'),
  ('French Southern Territories','TF','ATF'),
  ('Gabon','GA','GAB'),
  ('Gambia','GM','GMB'),
  ('Georgia','GE','GEO'),
  ('Germany','DE','DEU'),
  ('Ghana','GH','GHA'),
  ('Gibraltar','GI','GIB'),
  ('Greece','GR','GRC'),
  ('Greenland','GL','GRL'),
  ('Grenada','GD','GRD'),
  ('Guadeloupe','GP','GLP'),
  ('Guam','GU','GUM'),
  ('Guatemala','GT','GTM'),
  ('Guinea','GN','GIN'),
  ('Guinea-Bissau','GW','GNB'),
  ('Guyana','GY','GUY'),
  ('Haiti','HT','HTI'),
  ('Heard Island and Mcdonald Islands','HM','HMD'),
  ('Holy See (Vatican City State)','VA','VAT'),
  ('Honduras','HN','HND'),
  ('Hong Kong','HK','HKG'),
  ('Hungary','HU','HUN'),
  ('Iceland','IS','ISL'),
  ('India','IN','IND'),
  ('Indonesia','ID','IDN'),
  ('Iran, Islamic Republic of','IR','IRN'),
  ('Iraq','IQ','IRQ'),
  ('Ireland','IE','IRL'),
  ('Israel','IL','ISR'),
  ('Italy','IT','ITA'),
  ('Jamaica','JM','JAM'),
  ('Japan','JP','JPN'),
  ('Jordan','JO','JOR'),
  ('Kazakhstan','KZ','KAZ'),
  ('Kenya','KE','KEN'),
  ('Kiribati','KI','KIR'),
  ('Korea','KR','KOR'),
  ('Kuwait','KW','KWT'),
  ('Kyrgyzstan','KG','KGZ'),
  ('Lao People''s Democratic Republic','LA','LAO'),
  ('Latvia','LV','LVA'),
  ('Lebanon','LB','LBN'),
  ('Lesotho','LS','LSO'),
  ('Liberia','LR','LBR'),
  ('Libya','LY','LBY'),
  ('Liechtenstein','LI','LIE'),
  ('Lithuania','LT','LTU'),
  ('Luxembourg','LU','LUX'),
  ('Macao','MO','MAC'),
  ('Macedonia, the Former Yugoslav Republic of','MK','MKD'),
  ('Madagascar','MG','MDG'),
  ('Malawi','MW','MWI'),
  ('Malaysia','MY','MYS'),
  ('Maldives','MV','MDV'),
  ('Mali','ML','MLI'),
  ('Malta','MT','MLT'),
  ('Marshall Islands','MH','MHL'),
  ('Martinique','MQ','MTQ'),
  ('Mauritania','MR','MRT'),
  ('Mauritius','MU','MUS'),
  ('Mayotte','YT','MYT'),
  ('Mexico','MX','MEX'),
  ('Micronesia, Federated States of','FM','FSM'),
  ('Moldova, Republic of','MD','MDA'),
  ('Monaco','MC','MCO'),
  ('Mongolia','MN','MNG'),
  ('Albania','AL','ALB'),
  ('Montserrat','MS','MSR'),
  ('Morocco','MA','MAR'),
  ('Mozambique','MZ','MOZ'),
  ('Myanmar','MM','MMR'),
  ('Namibia','NA','NAM'),
  ('Nauru','NR','NRU'),
  ('Nepal','NP','NPL'),
  ('Netherlands','NL','NLD'),
  ('New Caledonia','NC','NCL'),
  ('New Zealand','NZ','NZL'),
  ('Nicaragua','NI','NIC'),
  ('Niger','NE','NER'),
  ('Nigeria','NG','NGA'),
  ('Niue','NU','NIU'),
  ('Norfolk Island','NF','NFK'),
  ('Northern Mariana Islands','MP','MNP'),
  ('Norway','NO','NOR'),
  ('Oman','OM','OMN'),
  ('Pakistan','PK','PAK'),
  ('Palau','PW','PLW'),
  ('Palestine, State of','PS','PSE'),
  ('Panama','PA','PAN'),
  ('Papua New Guinea','PG','PNG'),
  ('Paraguay','PY','PRY'),
  ('Peru','PE','PER'),
  ('Philippines','PH','PHL'),
  ('Pitcairn','PN','PCN'),
  ('Poland','PL','POL'),
  ('Portugal','PT','PRT'),
  ('Puerto Rico','PR','PRI'),
  ('Qatar','QA','QAT'),
  ('Reunion','RE','REU'),
  ('Romania','RO','ROM'),
  ('Russian Federation','RU','RUS'),
  ('Rwanda','RW','RWA'),
  ('Saint Helena','SH','SHN'),
  ('Saint Kitts and Nevis','KN','KNA'),
  ('Saint Lucia','LC','LCA'),
  ('Saint Pierre and Miquelon','PM','SPM'),
  ('Saint Vincent and the Grenadines','VC','VCT'),
  ('Samoa','WS','WSM'),
  ('San Marino','SM','SMR'),
  ('Sao Tome and Principe','ST','STP'),
  ('Saudi Arabia','SA','SAU'),
  ('Senegal','SN','SEN'),
  ('Seychelles','SC','SYC'),
  ('Sierra Leone','SL','SLE'),
  ('Singapore','SG','SGP'),
  ('Slovakia','SK','SVK'),
  ('Slovenia','SI','SVN'),
  ('Solomon Islands','SB','SLB'),
  ('Somalia','SO','SOM'),
  ('South Africa','ZA','ZAF'),
  ('South Georgia','GS','SGS'),
  ('Spain','ES','ESP'),
  ('Sri Lanka','LK','LKA'),
  ('Sudan','SD','SDN'),
  ('Suriname','SR','SUR'),
  ('Svalbard and Jan Mayen','SJ','SJM'),
  ('Swaziland','SZ','SWZ'),
  ('Sweden','SE','SWE'),
  ('Switzerland','CH','CHE'),
  ('Viet Nam','VN','VNM'),
  ('Virgin Islands (British)','VG','VGB'),
  ('Virgin Islands (U.S.)','VI','VIR'),
  ('Wallis and Futuna','WF','WLF'),
  ('Western Sahara','EH','ESH'),
  ('Yemen','YE','YEM'),
  ('Zambia','ZM','ZMB'),
  ('Zimbabwe','ZW','ZWE'),
  ('Afghanistan','AF','AFG'),
  ('Algeria','DZ','DZA');


UPDATE sys_countries
SET enabled = true
WHERE iso2 = 'NO';

UPDATE sys_countries
SET enabled = true
WHERE iso2 = 'SE';

UPDATE sys_countries
SET enabled = true
WHERE iso2 = 'DK';

UPDATE sys_countries
SET enabled = true
WHERE iso2 = 'FI';

UPDATE sys_countries
SET enabled = true
WHERE iso2 = 'FR';

UPDATE sys_countries
SET enabled = true
WHERE iso2 = 'DE';
---
ALTER TABLE "sys_countries" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "PUBLIC — Select"
  ON public.sys_countries
  FOR SELECT USING (true);