<template>
  <main>
    <block>
      <chat-question>
        How does direct dividend funds work? 
      </chat-question>
      <chat-answer>
        When you invest through Kalt, you are effectively buying a small piece of ownership in each of the fossil-free energy sites or artworks we own. This investment strategy allows you to diversify your portfolio and gain exposure to a wide range of fossil-free energy production sites, affordable housing units, small businesses and so much more, located all around the world.
      </chat-answer>
      <chat-answer>
        This way, you are not putting all your eggs in one basket and reducing the risk of your investment. 
      </chat-answer>
      <chat-answer>
        Additionally, by investing through our funds, you can also expect a steady stream of residual income, as the energy generated, art sold and homes built by us, will continually generate revenue for you as an investor.
      </chat-answer>
      <chat-question>
        What are dividends?
      </chat-question>
      <chat-answer>
        Dividends are a share of the profits generated by the assets in our funds, the direct part in the direct dividend fund name is the fact that we pay you on a daily basis, while dividends are traditionally paid out on a yearly or quarterly basis. Investing through our platform is a great way to earn a consistent income. 
      </chat-answer>
      <chat-answer>
        The second best part, you don't have to do anything.
      </chat-answer>
      <chat-answer>
        It's a great way to earn a return on your investment without doing anything. 
      </chat-answer>
      <chat-link to="/invest">
        invest now
      </chat-link>
    </block>
  </main>
</template>
<script lang="ts" setup>
  definePageMeta({
    pagename: 'What is a direct dividend fund?'
  })
  useHead({
    title: 'What is a direct dividend fund?',
    meta: [{
      name: 'description',
      content: 'Make money, make a difference.'
    }]
  })
  
</script>
<style scoped lang="scss">
  
</style>